### PR TITLE
Add link for sponsors

### PR DESCRIPTION
**Pull request by Besto**
ใส่ลิงค์ให้ที่ logo sponsor
แต่ยังไม่รู้ลิงค์ของ cleverse กับ pronto tools
No associated issue

### CODE REVIEW

**Comment by n3tr** [comment]
Thanks for contribute, I will find a remaining sponsor links for you. 👍 

cc @buffaly

**Review by dtinth — COMMENTED** [review]
@n3tr The code looks good. Don’t have any concerns, except whether these sponsor links should open in a new window or not.

**Comment by dtinth** [comment]
For Pronto Tools, I only found their Facebook page:

- https://www.facebook.com/prontotools/

**Comment by n3tr** [comment]
@Besto Agree, We should make link open in a new window.

@dtinth @PanJ Do you guys have link for Cleverse?

**Comment by n3tr** [comment]
@Besto Here is a link for Pronto tools and Cleverse

- http://www.prontotools.io
- http://cleverse.com

**Comment by Besto** [comment]
Updated

**Review by n3tr — APPROVED** [review]
LGTM

**Comment by dtinth** [comment]
Congratulations! Your PR has been merged. Please follow these steps to get your ticket.

1. Fill in this [form](https://www.eventpop.me/events/1809-react-bangkok-2-0-0/application_forms/109/applicants/new?token=VV8VYR4HCNLNYNDU).
2. Post your reference code at [reactbkk/contributors](https://gitter.im/reactbkk/contributors) to verify your GitHub account.
3. Wait for invitation email from Event Pop and follow the instruction from the email.

Thank you for your contribution. See you in the event!

**Pull request merged**
