### PR TITLE
Change color of Ticket button to improve visibility of user

### PR DESCRIPTION
**Pull request by up1**
เปลี่ยนสีปุ่ม Ticket เพื่อให้เด่นเป็นสง่าราศี

### CODE REVIEW

**Comment by dtinth** [comment]
Added screenshot for reference.

image

@buffaly What do you think?

**Comment by buffaly** [comment]
May be use blue in react CI~

**Review by dtinth — CHANGES_REQUESTED** [review]
Please use our blue color: `#00D8FF`

**Comment by buffaly** [comment]
For example~
image

**Comment by n3tr** [comment]
can we change color of hover state as well?

**Review by dtinth — APPROVED** [review]
This looks good now. Thank you~!

See you at React Bangkok 2.0.0!

**Pull request merged**
