### PR TITLE
[Features] Add favicon icon

### LINKED ISSUE #19: ใส่ favicon.ico

### PR DESCRIPTION
**Pull request by ratchagarn**
**1. Objective reason**

Website are missing favicon icon.
Related issue [#19](https://github.com/reactbkk/2.0.0/issues/19) 

**2. Description of change**

- Add favicon icon into static folder.
- Add link tag info head for display favicon icon.

---

Closes #19

### CODE REVIEW

**Review by dtinth — CHANGES_REQUESTED** [review]
Hello, and thanks for the PR!

However, it seems that the icon is a generic React icon, and not an icon for React Bangkok group.

image

You can find our logo on our [organization page](https://github.com/reactbkk) and we also have the `.svg` version inside this repository.

**Comment by dtinth** [comment]
Please note that `.svg` files cannot be used as an icon. See #34 for more information.

**Comment by ratchagarn** [comment]
@dtinth Thanks for your comment.
I forgot about that icon need to be React Bangkok group.
Sorry about that.

**Comment by dtinth** [comment]
image

**Comment by ratchagarn** [comment]
OK guy. Just need only flower right?

**Comment by dtinth** [comment]
@ratchagarn Yes. Just the lotus in the center ;)

**Comment by dtinth** [comment]
@ratchagarn Would be good if you make the corner a bit rounded, like in your first commit

**Comment by ratchagarn** [comment]
@dtinth OK as your wish.

**Comment by dtinth** [comment]
ขอบคุณครับบ แต่รู้สึกเหมือนกลีบดอกบัวมันจมลงไปในช่องว่างกลมๆ ตรงกลางน่ะครับ 😄

image

**Comment by ratchagarn** [comment]
@dtinth 😭 Got it. I'm not proficient in graphic application. Will try again. 😭

**Review by dtinth — APPROVED** [review]

**Comment by dtinth** [comment]
This looks good!

I will merge the PR now.

You’ll be updated with the tickets information soon.

Thank you for your effort 😃

**Comment by ratchagarn** [comment]
Thanks ! 😄

**Pull request merged**
