### PR TITLE
Add more hero background images

### LINKED ISSUE #7: Add photos section
If you would like to work on this issue, please leave a comment on this issue.
Also, in the PR, please write `Closes #7` in the pull request’s __description.__

### PR DESCRIPTION
**Pull request by turboza**
Closes #7

**Why?**
- We need more hero background images, as for now we have only 3 images.

**What?**
- Add hero background images up to 5 images. 
- Optimize images more as we don't need high quality for background under overlay

Bonus: Page load speed as "Good 3G" preset in chrome is reduced
- master branch : ~6.0s 
- this branch : ~4.3s 

---

~However, it raises a problem. As I tested in chrome with the "Good 3G" throttle preset. It takes a lot more time to load.~

~At the end of the day, I further reduce the image quality as they don't need to be high quality to be a background under overlay. And pick only 5 to load after shuffling.~

~Side effect: Got this warning from images shuffling. But no warning in static build. I guess it's from the Next.js that re-execute the JS.~ (Resolved by remove all randomization)

### CODE REVIEW

**Comment by dtinth** [comment]
@turboza 

I think the missing photos are related to the photos section (see #7). Putting 10 photos in that section wouldn't hurt the page performance as much, I guess.

In my opinion, only three photos for the hero unit are enough.

**Comment by turboza** [comment]
@dtinth Oh, I missed that issue. And thanks for the idea, I eventually just load 5 images to display. But I'm not sure if I could ignore the warning I posted in desc.

**Comment by dtinth** [comment]
@turboza The error causes React to not be able to re-use prerendered markup... Better pick just 5 best photos.

**Comment by turboza** [comment]
@dtinth fixed as your suggestion. Please review again krub

**Comment by dtinth** [comment]
It looks good now~ Thanks @turboza

**Review by dtinth — APPROVED** [review]

**Pull request merged**
