### PR TITLE
set Theme color on chrome

### PR DESCRIPTION
**Pull request by TonPC64**

### CODE REVIEW

**Comment by dtinth** [comment]
Hello, thank you for the PR.

The code looks good, but I am outside right now, therefore, I cannot test it. Could you please add a screenshot so that we can verify that it is working on an Android phone? Thank you.

**Comment by TonPC64** [comment]
alt text

**Review by dtinth — APPROVED** [review]

**Comment by n3tr** [comment]
better move it to manifest.json?

**Comment by TonPC64** [comment]
okay i will try

**Comment by n3tr** [comment]
@kingkong64 just asking, this also looks good to me.

**Comment by n3tr** [comment]
@kingkong64 I think better we add it to both meta tag and manifest.json 😄 

https://developers.google.com/web/tools/lighthouse/audits/address-bar

**Comment by TonPC64** [comment]
yes if add on menifest.js only this don't work.

**Comment by n3tr** [comment]
LGTM, Thanks for your help. 

your ticket is on the way. 🎉

**Comment by n3tr** [comment]
resolves #89

**Pull request merged**
